AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SQS to SNS (Java 17 Lambda).

Parameters:
  SQSQueueArn:
    Type: String
    Description: The ARN of the SQS Queue

Resources:
  SqsToSnsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pankajoj-sqs-to-sns-java
      CodeUri: target/lambda-0.0.1-SNAPSHOT.jar
      Handler: com.lambda.handler.SqsToSnsLambdaHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      Timeout: 30
      MemorySize: 512

      Policies:
        - AWSLambda_FullAccess 
        - AWSLambdaSQSQueueExecutionRole 
        - AmazonSNSFullAccess 
        - AmazonSQSFullAccess

      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref SQSQueueArn
            BatchSize: 10
